name: NCI
channels:
  - pytorch
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=4.5=1_gnu
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.4=pyhd8ed1ab_0
  - blas=1.0=mkl
  - bottleneck=1.3.2=py38heb32a55_1
  - bzip2=1.0.8=h7b6447c_0
  - ca-certificates=2022.07.19=h06a4308_0
  - certifi=2022.6.15=py38h06a4308_0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - debugpy=1.5.1=py38h295c915_0
  - decorator=5.1.0=pyhd8ed1ab_0
  - entrypoints=0.3=pyhd8ed1ab_1003
  - ffmpeg=4.3=hf484d3e_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - gmp=6.2.1=h2531618_2
  - gnutls=3.6.15=he1e5248_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - ipykernel=6.6.0=py38he5a9106_0
  - ipython=7.30.1=py38h578d9bd_0
  - jedi=0.18.1=py38h578d9bd_0
  - joblib=1.1.0=pyhd3eb1b0_0
  - jpeg=9d=h7f8727e_0
  - jsonlines=3.1.0=pyhd8ed1ab_0
  - jupyter_client=7.1.0=pyhd8ed1ab_0
  - jupyter_core=4.9.1=py38h578d9bd_1
  - lame=3.100=h7b6447c_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.3.0=h5101ec6_17
  - libgfortran-ng=7.5.0=ha8ba4b0_17
  - libgfortran4=7.5.0=ha8ba4b0_17
  - libgomp=9.3.0=h5101ec6_17
  - libiconv=1.15=h63c8f33_5
  - libidn2=2.3.2=h7f8727e_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h36c2ea0_1
  - libstdcxx-ng=9.3.0=hd4cf53a_17
  - libtasn1=4.16.0=h27cfd23_0
  - libtiff=4.2.0=h85742a9_0
  - libunistring=0.9.10=h27cfd23_0
  - libuv=1.40.0=h7b6447c_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - matplotlib-inline=0.1.3=pyhd8ed1ab_0
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py38h7f8727e_0
  - mkl_fft=1.3.1=py38hd3c417c_0
  - mkl_random=1.2.2=py38h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - nest-asyncio=1.5.4=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - nltk=3.6.5=pyhd3eb1b0_0
  - numexpr=2.7.3=py38h22e1b3c_1
  - numpy-base=1.21.5=py38hf524024_2
  - olefile=0.46=pyhd3eb1b0_0
  - openh264=2.1.0=hd408876_0
  - openssl=1.1.1q=h7f8727e_0
  - pandas=1.3.4=py38h8c16a72_0
  - parso=0.8.3=pyhd8ed1ab_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pillow=8.4.0=py38h5aabda8_0
  - pip=21.2.4=py38h06a4308_0
  - prompt-toolkit=3.0.24=pyha770c72_0
  - ptyprocess=0.7.0=pyhd3deb0d_0
  - pygments=2.10.0=pyhd8ed1ab_0
  - python=3.8.12=h12debd9_0
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.8=2_cp38
  - pytorch=1.10.0=py3.8_cuda11.3_cudnn8.2.0_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.3=pyhd3eb1b0_0
  - pyzmq=19.0.2=py38ha71036d_2
  - readline=8.1=h27cfd23_0
  - scikit-learn=1.0.2=py38h51133e4_1
  - scipy=1.7.3=py38hc147768_0
  - setuptools=58.0.4=py38h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - threadpoolctl=2.2.0=pyh0d69192_0
  - tk=8.6.11=h1ccaba5_0
  - torchaudio=0.10.0=py38_cu113
  - torchvision=0.11.1=py38_cu113
  - tornado=6.1=py38h497a2fe_1
  - tqdm=4.62.3=pyhd3eb1b0_1
  - traitlets=5.1.1=pyhd8ed1ab_0
  - typing_extensions=3.10.0.2=pyh06a4308_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.4=h9c3ff4c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - absl-py==1.0.0
    - aiohttp==3.8.1
    - aiosignal==1.2.0
    - async-timeout==4.0.1
    - attrs==21.2.0
    - cachetools==4.2.4
    - charset-normalizer==2.0.9
    - click==8.0.3
    - configparser==5.2.0
    - dill==0.3.4
    - docker-pycreds==0.4.0
    - filelock==3.4.0
    - frozenlist==1.2.0
    - fsspec==2021.11.1
    - future==0.18.2
    - gitdb==4.0.9
    - gitpython==3.1.24
    - google-auth==2.3.3
    - google-auth-oauthlib==0.4.6
    - grpcio==1.42.0
    - idna==3.3
    - importlib-metadata==4.8.2
    - markdown==3.3.6
    - multidict==5.2.0
    - nlp==0.4.0
    - numpy==1.21.4
    - oauthlib==3.1.1
    - packaging==21.3
    - pathtools==0.1.2
    - promise==2.3
    - protobuf==3.19.1
    - psutil==5.8.0
    - pyarrow==6.0.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pydeprecate==0.3.1
    - pyparsing==3.0.6
    - pytorch-lightning==1.4.9
    - pyyaml==6.0
    - regex==2021.11.10
    - requests==2.26.0
    - requests-oauthlib==1.3.0
    - rsa==4.8
    - sacremoses==0.0.46
    - sentencepiece==0.1.96
    - sentry-sdk==1.5.0
    - shortuuid==1.0.8
    - smmap==5.0.0
    - subprocess32==3.5.4
    - tensorboard==2.7.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.0
    - termcolor==1.1.0
    - tokenizers==0.9.2
    - torchmetrics==0.6.1
    - transformers==3.4.0
    - urllib3==1.26.7
    - wandb==0.12.7
    - werkzeug==2.0.2
    - xxhash==2.0.2
    - yarl==1.7.2
    - yaspin==2.1.0
    - zipp==3.6.0
prefix: /home/corpusindex/anaconda3/envs/corpus
